name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: |
          backend/package-lock.json
          todo-app/package-lock.json

    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: Install frontend dependencies
      run: |
        cd todo-app
        npm ci

    - name: Build frontend
      run: |
        cd todo-app
        npm run build

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build -t backend ./backend
        docker build -t frontend ./todo-app

    - name: Test Docker containers
      run: |
        docker-compose up -d
        sleep 15
        # Test backend health endpoint
        curl -f http://localhost:4000/health || (echo "Backend health check failed" && docker-compose logs backend && exit 1)
        # Test frontend
        curl -f http://localhost:3000 || (echo "Frontend check failed" && docker-compose logs frontend && exit 1)
        docker-compose down
